### ISSUE TITLE
Coveralls does not seem to detect my branch

### ISSUE THREAD

**Issue by WeAreDevo** [Michael-Beukman/3KleinGroup#1]
Using cobertura to produce coverage data and the coveralls graddle plugin as specified here:
https://github.com/kt3k/coveralls-gradle-plugin

Upon pushing, all seems to build successfully with circleci but coveralls badge in my branch's README shows unknown.
I've tried resyncing coveralls with the github repo but maybe you have to try resyncing Mike?

Or I'm just not generating the coverage data coveralls need XD

**Comment by Michael-Beukman** [comment]
This doesn't seem to be a coveralls issue. The android code coverage tools do not give any code coverage (everything is N/A)

**Comment by WeAreDevo** [comment]
This also might be a problem:
https://stackoverflow.com/questions/50903389/how-to-upload-test-reports-of-kotlin-sources-to-coveralls

**Comment by Michael-Beukman** [comment]
Tests that I'm running locally also seem to not generate any code coverage, so it's not necessarily a coveralls problem.

**Comment by Michael-Beukman** [comment]
Stuff seems to be less broken when you move all of the cobertura stuff from build.gradle to app/build.gradle. It now says 0% coverage instead of N/A

**Comment by Michael-Beukman** [comment]
Coveralls coverage is working now. Moving other problem to new issue
