### ISSUE TITLE
Login Trouble

### ISSUE THREAD

**Issue by Michael-Beukman** [Michael-Beukman/3KleinGroup#5]
Sometimes when I try to log in, the app returns 'acc failed'. I'm not sure why

**Comment by Matkicail** [comment]
I had a recent problem with it too, I wasn't having that issue in the initialSetUp version, I will have a look at it again. Try and find out what it is since Google does provide an error code for some problems.

**Comment by Michael-Beukman** [comment]
The problem has been fixed on my side, and it's working.
